Removed gammapy dependency
cositools/cosipy pull request #14
Opened 2023-04-06 18:48 UTC by eneights

Altered detector response to use astromodels instead of gammapy, and changed format of config file to be compatible with astromodels

2023-04-11 20:44 UTC, israelmcmc requested changes
Thanks, @eneights! I haven't run all this yet, but it seems like it should accomplish the intended changes. Most of these comments are about style.

One general comment, before I forget: once we get this running, the integration code should be part of 3ML/astromodels instead.

2023-04-11 20:44 UTC, israelmcmc commented on docs/tutorials/DetectorResponse.ipynb
> +    "spectrum = Powerlaw()\n",
These different parameters are already Quantities. Instead of doing e.g.
```
spectrum.K.value = Quantity(K) / Quantity(K).unit
spectrum.K.unit = Quantity(K).unit
```
You can do
```
spectrum.K.value = K.value
spectrum.K.unit = K.unit
```
Maybe you can even try if you can simply do this, although I'm not sure it'll work
```
spectrum.K = K
```

2023-04-11 20:44 UTC, israelmcmc commented on .DS_Store
.DS_store files shouldn't be part of the PR. I'll make an issue to add this to the .gitignore file, but for now, can you remove them, please?

2023-04-11 20:44 UTC, israelmcmc commented on cosipy/response/FullDetectorResponse.py
> +            spectrum_module = importlib.import_module('astromodels.core.model_parser')
I used `importlib` because I had to parse the model class. In this case you are importing the parser itself (a class), so you can just add the include at the top of the file
```
from astromodels.core.model_parser import ModelParser
```

2023-04-11 20:44 UTC, israelmcmc commented on cosipy/response/FullDetectorResponse.py
> +            expectation = psr.get_expectation(spectrum).project('Em') ######
Extra ###. Benign, but it makes it seems like this line changed during review/debugging

2023-04-11 20:44 UTC, israelmcmc commented on cosipy/response/PointSourceResponse.py
> +from threeML import *
For quick script this is fine, but for long-term maintained code using `import *` is not the best practice since this pollutes the environment with unnecessary variables that can collide with other libraries. It's better to list each variable you want to import

2023-04-11 20:44 UTC, israelmcmc commented on cosipy/response/PointSourceResponse.py
> +        if (isinstance(spectrum, Blackbody) or isinstance(spectrum, ModifiedBlackbody) or isinstance(spectrum, NonDissipativePhotosphere) or
There should be a better way to get the unit of the spectrum, independently of the actual class. Let's talk with the 3ML folks.

2023-04-11 20:45 UTC, israelmcmc commented
See also https://github.com/cositools/intro_cosipy/pull/2

2023-04-17 20:20 UTC, eneights commented on docs/tutorials/DetectorResponse.ipynb
> +    "spectrum = Powerlaw()\n",
This is fixed in the latest commit.

`spectrum.K = K` does not work

2023-04-17 20:21 UTC, eneights commented on .DS_Store
Removed!

2023-04-17 20:21 UTC, eneights commented on cosipy/response/FullDetectorResponse.py
> +            spectrum_module = importlib.import_module('astromodels.core.model_parser')
This has been fixed

2023-04-17 20:21 UTC, eneights commented on cosipy/response/FullDetectorResponse.py
> +            expectation = psr.get_expectation(spectrum).project('Em') ######
Whoops, didn't mean to leave that in there. Fixed!

2023-04-17 20:22 UTC, eneights commented on cosipy/response/PointSourceResponse.py
> +from threeML import *
Updated to import each model

2023-04-17 20:24 UTC, eneights commented on cosipy/response/PointSourceResponse.py
> +        if (isinstance(spectrum, Blackbody) or isinstance(spectrum, ModifiedBlackbody) or isinstance(spectrum, NonDissipativePhotosphere) or
Didn't change this in the latest commit. Will plan to change this before incorporating the integration into the 3ML code

2023-04-28 22:04 UTC, israelmcmc commented on cosipy/response/PointSourceResponse.py
> +from threeML import *
Thanks. This should change again after we modify 3ML to do the integration.

2023-04-28 22:08 UTC, israelmcmc commented on cosipy/response/PointSourceResponse.py
> +        if (isinstance(spectrum, Blackbody) or isinstance(spectrum, ModifiedBlackbody) or isinstance(spectrum, NonDissipativePhotosphere) or
Ok. I'll open an issue to remember this.

2023-04-28 22:11 UTC, israelmcmc commented on .DS_Store
Hmmm most are still there in the "Files changed" tab 🙃 . I'll PM you.

2023-04-28 22:12 UTC, israelmcmc commented on cosipy/response/PointSourceResponse.py
> +        if (isinstance(spectrum, Blackbody) or isinstance(spectrum, ModifiedBlackbody) or isinstance(spectrum, NonDissipativePhotosphere) or
Sounds good. I'll open an issue about this to remember us

2023-05-02 13:58 UTC, eneights commented on .DS_Store
They should actually be gone now!

2023-05-02 14:00 UTC, eneights commented
I moved the COSILike class to cosipy.threeml and added an example notebook for the spectral fit

2023-05-03 07:41 UTC, merged