Merging `spacecraftpositionattitude` and `orientation` module
cositools/cosipy pull request #72
Opened 2023-08-16 06:25 UTC by Yong2Sheng

spacecraftpositionattitude and orientation are merged into a single module called `SpacecraftFile`.

Run the notebook *Point_source_resonse.ipynb* in the tutorial folder to check out how it works!

Thanks!

2023-09-08 22:39 UTC, Yong2Sheng commented
The npy files has been updaed.

2023-09-12 01:13 UTC, israelmcmc commented
Thanks for working in this, @Yong2Sheng! 

- Your notebook works for me. 
- In order to make the SpectralFitting notebook run, I had to do some changes to your code. Basically, change the call to the class within the class itself. See my suggested changes. In addition, the notebook itself need to changes to use this class, but this can be done in an separate PR. I'll open an issue (heads up @eneights )
- I think some files were committed by accident, or are not where data should go. Please see my comments.
- Can you also remove the older @saurabhmittal23's class, please?

After these small changes I think this can be merges.

2023-09-12 01:13 UTC, israelmcmc requested changes

2023-09-12 01:13 UTC, israelmcmc commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        Returns the Orientation file class object for the source time
```suggestion
        Returns the SpacecraftFile file class object for the source time
```

2023-09-12 01:13 UTC, israelmcmc commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        cosipy.Orientation
```suggestion
        cosipy.SpacecraftFile
```

2023-09-12 01:13 UTC, israelmcmc commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        return Orientation_file(new_times, new_x_direction, new_z_direction)
```suggestion
        return self.__class__(new_times, new_x_direction, new_z_direction)
```

2023-09-12 01:13 UTC, israelmcmc commented on cosipy/spacecraftfile/Module_coding.ipynb
Please remove this file from the Pull Request

2023-09-12 01:13 UTC, israelmcmc commented on docs/tutorials/Pointings/Cygx1_balloon_dtpoins_remove_none.npy
This and the other files in Pointing should be in the `cosipy/test_data` folder instead

2023-09-12 01:13 UTC, israelmcmc commented on docs/tutorials/Response/test_full_detector_response.h5
Please remove this file and use the one from `cosipy/test_data` instead

2023-09-13 14:27 UTC, Yong2Sheng commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        Returns the Orientation file class object for the source time
change applied

2023-09-13 14:28 UTC, Yong2Sheng commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        cosipy.Orientation
changes applied

2023-09-13 14:28 UTC, Yong2Sheng commented on cosipy/spacecraftfile/SpacecraftFile.py
> +        return Orientation_file(new_times, new_x_direction, new_z_direction)
changes applied

2023-09-13 14:29 UTC, Yong2Sheng commented on cosipy/spacecraftfile/Module_coding.ipynb
removed

2023-09-13 14:53 UTC, Yong2Sheng commented on docs/tutorials/Pointings/Cygx1_balloon_dtpoins_remove_none.npy
Moved the files to `cosipy/test_data` and changed the notebook accordingly so that it can read the data from the new location in `cosipy/test_data`.

2023-09-13 14:57 UTC, Yong2Sheng commented on docs/tutorials/Response/test_full_detector_response.h5
Remove the file, and notebook now reads response from `cosipy/test_data`.

2023-09-20 15:17 UTC, israelmcmc approved these changes
Thanks @Yong2Sheng , looks good to me. I'll merge.

2023-09-20 15:17 UTC, merged